import { defineStore } from 'pinia'
import { date } from 'quasar'
import { api } from 'src/boot/axios'

export const useRencanaPemesananObatStore = defineStore('store_rencana_pemesanan_obat', {
  state: () => ({
    loading: false,
    items: [],
    param: {
      no_rencbeliobat: '',
      per_page: 10,
      tanggal: date.formatDate(Date.now(), 'YYYY-MM-DD')
    },
    form: {
      tanggal: date.formatDate(Date.now(), 'YYYY-MM-DD')
    },
    disp: {
      tanggal: date.formatDate(Date.now(), 'DD MMMM YYYY')
    },
    columns: [],
    columnHide: ['id', 'created_at', 'updated_at', 'deleted_at'],
    obats: [
      {
        id: 1,
        kd_obat: '00001-FAR',
        nama_obat: 'obat anu 24 MG 10 ML KAPSUL',
        merk: 'sanbal',
        kandungan: 'allopurinol',
        jenis_perbekalan: 'BMHP',
        bentuk_sediaan: 'KAPSUL',
        kode108: '1.1.7.01.04.01.001',
        uraian108: 'Obat Cair',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'sch',
        satuan_k: 'Papan',
        kelompok_psikotropika: '0',
        kelompok_penyimpanan: 'Rak dalam',
        kelompok_rko: 'Albumin serum normal (human albumin) inj 20% 100 ml',
        status_generik: '0',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '24 MG',
        volumesediaan: '10 ML',
        kelas_terapi: 'kellas bulu',
        nilai_kdn: 12312.00,
        sertifikat_kdn: 'asdasdas',
        sistembayar: 'UMUM',
        created_at: '2023-06-25 10:16:22',
        updated_at: '2023-06-24 02:38:43',
        deleted_at: null
      },
      {
        id: 2,
        kd_obat: '00007-FAR',
        nama_obat: 'wew 24 MG 120 PUFF LARUTAN sanpo',
        merk: 'sanpo',
        kandungan: 'Akarbose',
        jenis_perbekalan: 'Alkes Habis Pakai',
        bentuk_sediaan: 'LARUTAN',
        kode108: '1.1.7.01.04.01.002',
        uraian108: 'Obat Padat',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'Gelas',
        satuan_k: 'belum ada satuan',
        kelompok_psikotropika: '0',
        kelompok_penyimpanan: 'Salep-salepan',
        kelompok_rko: 'Albumin serum normal (human albumin) inj 20% 100 ml',
        status_generik: '0',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '24 MG',
        volumesediaan: '120 PUFF',
        kelas_terapi: 'kelas anu',
        nilai_kdn: 0.00,
        sertifikat_kdn: 'ddddd',
        sistembayar: 'SEMUA',
        created_at: '2023-06-25 10:16:09',
        updated_at: '2023-06-24 16:50:16',
        deleted_at: null
      },
      {
        id: 3,
        kd_obat: '00008-FAR',
        nama_obat: 'wew 250 MG 5 GRAM TABLET',
        merk: 'kalbe',
        kandungan: 'Akarbose',
        jenis_perbekalan: 'Obat',
        bentuk_sediaan: 'TABLET',
        kode108: '1.1.7.01.04.01.002',
        uraian108: 'Obat Padat',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'Gelas',
        satuan_k: 'cup',
        kelompok_psikotropika: '1',
        kelompok_penyimpanan: 'Rak dalam',
        kelompok_rko: 'Albendazol tab 400 mg',
        status_generik: '1',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '250 MG',
        volumesediaan: '5 GRAM',
        kelas_terapi: 'kelas anak',
        nilai_kdn: 0.00,
        sertifikat_kdn: 'ddddd',
        sistembayar: 'BPJS',
        created_at: '2023-06-25 10:15:57',
        updated_at: '2023-06-24 16:51:15',
        deleted_at: null
      },
      {
        id: 4,
        kd_obat: '00009-FAR',
        nama_obat: 'wewea wew 20 MG 15 GRAM LARUTAN Mercon',
        merk: 'Mercon',
        kandungan: 'aminophilin',
        jenis_perbekalan: 'Reagen',
        bentuk_sediaan: 'LARUTAN',
        kode108: '1.1.7.01.04.01.001',
        uraian108: 'Obat Cair',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'jrigen',
        satuan_k: 'Tube',
        kelompok_psikotropika: '1',
        kelompok_penyimpanan: 'Rak dalam',
        kelompok_rko: 'Albendazol tab 400 mg',
        status_generik: '1',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '20 MG',
        volumesediaan: '15 GRAM',
        kelas_terapi: 'kelas anak',
        nilai_kdn: 0.00,
        sertifikat_kdn: 'ddddd',
        sistembayar: 'SEMUA',
        created_at: '2023-06-26 07:35:42',
        updated_at: '2023-06-24 17:04:10',
        deleted_at: null
      },
      {
        id: 5,
        kd_obat: '00010-FAR',
        nama_obat: 'coab baru 400 MG 5 GRAM TABLET',
        merk: 'Mercon',
        kandungan: 'amidaron',
        jenis_perbekalan: 'Obat',
        bentuk_sediaan: 'TABLET',
        kode108: '1.1.7.01.04.01.002',
        uraian108: 'Obat Padat',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'belum ada satuan',
        satuan_k: 'sch',
        kelompok_psikotropika: '0',
        kelompok_penyimpanan: 'Rak dalam',
        kelompok_rko: 'Albendazol susp 200 mg/5 ml',
        status_generik: '0',
        status_forkid: '0',
        status_fornas: '0',
        kekuatan_dosis: '400 MG',
        volumesediaan: '5 GRAM',
        kelas_terapi: 'KElas berat',
        nilai_kdn: 34234.00,
        sertifikat_kdn: 'dsadas',
        sistembayar: 'UMUM',
        created_at: '2023-06-26 07:37:03',
        updated_at: '2023-06-26 07:37:03',
        deleted_at: null
      },
      {
        id: 6,
        kd_obat: '00012-FAR',
        nama_obat: 'VACUM BLOOD COCTION TUBE CLOT AKTIVATOR 2 MG 3 ML LARUTAN ARKAN',
        merk: 'ARKAN',
        kandungan: 'Abakavir',
        jenis_perbekalan: 'Alkes Habis Pakai',
        bentuk_sediaan: 'LARUTAN',
        kode108: '1.1.7.01.06.01.003',
        uraian108: 'PERSEDIAAN UNTUK TUJUAN STRATEGI BERJAGA-JAGA',
        kode50: '5.1.02.01.01.042',
        uraian50: 'PERSEDIAAN UNTUK TUJUAN STRATEGI BERJAGA-JAGA',
        satuan_b: 'Box',
        satuan_k: 'Pcs',
        kelompok_psikotropika: '1',
        kelompok_penyimpanan: 'RAK ALKES',
        kelompok_rko: 'Albumin serum normal (human albumin) inj 20% 100 ml',
        status_generik: '1',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '2 MG',
        volumesediaan: '3 ML',
        kelas_terapi: 'Kelas ringan',
        nilai_kdn: 90.00,
        sertifikat_kdn: '909',
        sistembayar: 'SEMUA',
        created_at: '2023-06-27 09:12:39',
        updated_at: '2023-06-27 09:11:51',
        deleted_at: null
      },
      {
        id: 7,
        kd_obat: '00013-FAR',
        nama_obat: 'Wew asdas TABLET',
        merk: '',
        kandungan: '',
        jenis_perbekalan: '',
        bentuk_sediaan: 'TABLET',
        kode108: '',
        uraian108: '',
        kode50: '',
        uraian50: '',
        satuan_b: '',
        satuan_k: '',
        kelompok_psikotropika: '',
        kelompok_penyimpanan: '',
        kelompok_rko: '',
        status_generik: '',
        status_forkid: '',
        status_fornas: '',
        kekuatan_dosis: '',
        volumesediaan: '',
        kelas_terapi: '',
        nilai_kdn: 0.00,
        sertifikat_kdn: '',
        sistembayar: '',
        created_at: '2023-06-27 10:11:10',
        updated_at: '2023-06-27 10:11:10',
        deleted_at: null
      },
      {
        id: 8,
        kd_obat: '00014-FAR',
        nama_obat: 'KLINDAMISIN  150 MG KAPSUL',
        merk: 'DEXA MEDICA',
        kandungan: 'Klindamisin',
        jenis_perbekalan: 'Obat',
        bentuk_sediaan: 'KAPSUL',
        kode108: '1.1.7.01.04.01.002',
        uraian108: 'Obat Padat',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'Box',
        satuan_k: 'Kapsul',
        kelompok_psikotropika: '0',
        kelompok_penyimpanan: 'RAK TABLET',
        kelompok_rko: 'Klindamisin kaps 150 mg',
        status_generik: '1',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '150 MG',
        volumesediaan: '-',
        kelas_terapi: 'Antibiotik',
        nilai_kdn: 33.30,
        sertifikat_kdn: '4468/SJ-IND.8/TKDN/9/2022',
        sistembayar: 'SEMUA',
        created_at: '2023-06-27 16:45:28',
        updated_at: '2023-06-27 16:45:28',
        deleted_at: null
      },
      {
        id: 9,
        kd_obat: '00017-FAR',
        nama_obat: 'Obat baru saja 50 MG 1 GRAM LARUTAN',
        merk: 'sanbal',
        kandungan: 'ampicillin',
        jenis_perbekalan: 'Obat',
        bentuk_sediaan: 'LARUTAN',
        kode108: '1.1.7.01.04.01.001',
        uraian108: 'Obat Cair',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'Sisir',
        satuan_k: 'sch',
        kelompok_psikotropika: '0',
        kelompok_penyimpanan: 'RAK TABLET',
        kelompok_rko: 'Albumin serum normal (human albumin) inj 20% 100 ml',
        status_generik: '1',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '50 MG',
        volumesediaan: '1 GRAM',
        kelas_terapi: 'KElas berat',
        nilai_kdn: 13.00,
        sertifikat_kdn: 'sfsads',
        sistembayar: 'SEMUA',
        created_at: '2023-07-03 03:24:21',
        updated_at: '2023-07-03 03:24:21',
        deleted_at: null
      },
      {
        id: 10,
        kd_obat: '00020-FAR',
        nama_obat: 'anu',
        merk: '',
        kandungan: '',
        jenis_perbekalan: 'Obat',
        bentuk_sediaan: '',
        kode108: '',
        uraian108: '',
        kode50: '',
        uraian50: '',
        satuan_b: '',
        satuan_k: '',
        kelompok_psikotropika: '',
        kelompok_penyimpanan: '',
        kelompok_rko: '',
        status_generik: '',
        status_forkid: '',
        status_fornas: '',
        kekuatan_dosis: '',
        volumesediaan: '',
        kelas_terapi: '',
        nilai_kdn: 0.00,
        sertifikat_kdn: '',
        sistembayar: '',
        created_at: '2023-07-03 14:36:58',
        updated_at: '2023-07-03 14:36:58',
        deleted_at: null
      },
      {
        id: 11,
        kd_obat: '00022-FAR',
        nama_obat: 'obat',
        merk: '',
        kandungan: '',
        jenis_perbekalan: '',
        bentuk_sediaan: '',
        kode108: '',
        uraian108: '',
        kode50: '',
        uraian50: '',
        satuan_b: '',
        satuan_k: '',
        kelompok_psikotropika: '',
        kelompok_penyimpanan: '',
        kelompok_rko: '',
        status_generik: '',
        status_forkid: '',
        status_fornas: '',
        kekuatan_dosis: '',
        volumesediaan: '',
        kelas_terapi: '',
        nilai_kdn: 0.00,
        sertifikat_kdn: '',
        sistembayar: '',
        created_at: '2023-07-03 14:37:54',
        updated_at: '2023-07-03 14:37:54',
        deleted_at: null
      },
      {
        id: 12,
        kd_obat: '00024-FAR',
        nama_obat: 'terapi',
        merk: '',
        kandungan: '',
        jenis_perbekalan: '',
        bentuk_sediaan: '',
        kode108: '',
        uraian108: '',
        kode50: '',
        uraian50: '',
        satuan_b: '',
        satuan_k: '',
        kelompok_psikotropika: '',
        kelompok_penyimpanan: '',
        kelompok_rko: '',
        status_generik: '',
        status_forkid: '',
        status_fornas: '',
        kekuatan_dosis: '',
        volumesediaan: '',
        kelas_terapi: '',
        nilai_kdn: 0.00,
        sertifikat_kdn: '',
        sistembayar: '',
        created_at: '2023-07-04 11:02:14',
        updated_at: '2023-07-04 11:02:14',
        deleted_at: null
      },
      {
        id: 13,
        kd_obat: '00026-FAR',
        nama_obat: 'anu',
        merk: '',
        kandungan: '',
        jenis_perbekalan: '',
        bentuk_sediaan: '',
        kode108: '',
        uraian108: '',
        kode50: '',
        uraian50: '',
        satuan_b: '',
        satuan_k: '',
        kelompok_psikotropika: '',
        kelompok_penyimpanan: '',
        kelompok_rko: '',
        status_generik: '',
        status_forkid: '',
        status_fornas: '',
        kekuatan_dosis: '',
        volumesediaan: '',
        kelas_terapi: '',
        nilai_kdn: 0.00,
        sertifikat_kdn: '',
        sistembayar: '',
        created_at: '2023-07-04 11:05:55',
        updated_at: '2023-07-04 11:05:55',
        deleted_at: null
      },
      {
        id: 14,
        kd_obat: '00028-FAR',
        nama_obat: 'sada',
        merk: '',
        kandungan: '',
        jenis_perbekalan: '',
        bentuk_sediaan: '',
        kode108: '',
        uraian108: '',
        kode50: '',
        uraian50: '',
        satuan_b: '',
        satuan_k: '',
        kelompok_psikotropika: '',
        kelompok_penyimpanan: '',
        kelompok_rko: '',
        status_generik: '',
        status_forkid: '',
        status_fornas: '',
        kekuatan_dosis: '',
        volumesediaan: '',
        kelas_terapi: '',
        nilai_kdn: 0.00,
        sertifikat_kdn: '',
        sistembayar: '',
        created_at: '2023-07-03 00:08:12',
        updated_at: '2023-07-03 00:08:12',
        deleted_at: null
      },
      {
        id: 15,
        kd_obat: '00029-FAR',
        nama_obat: 'Klindamisin 150 MG KAPSUL',
        merk: 'Contoh',
        kandungan: 'Klindamisin',
        jenis_perbekalan: 'Obat',
        bentuk_sediaan: 'KAPSUL',
        kode108: '1.1.7.01.04.01.002',
        uraian108: 'Obat Padat',
        kode50: '5.1.02.01.01.037',
        uraian50: 'BELANJA OBAT-OBATAN',
        satuan_b: 'Box',
        satuan_k: 'Kapsul',
        kelompok_psikotropika: '0',
        kelompok_penyimpanan: 'RAK TABLET',
        kelompok_rko: 'Klindamisin kaps 150 mg',
        status_generik: '1',
        status_forkid: '1',
        status_fornas: '1',
        kekuatan_dosis: '150 MG',
        volumesediaan: '',
        kelas_terapi: '',
        nilai_kdn: 3.00,
        sertifikat_kdn: '',
        sistembayar: 'SEMUA',
        created_at: '2023-07-05 14:42:16',
        updated_at: '2023-07-05 14:42:16',
        deleted_at: null
      }
    ],
    stoksGudangs: [],
    stoksRSes: [],
    stoksMaksRs: 0
  }),
  actions: {
    setForm(key, val) {
      this.form[key] = val
    },
    setParam(key, val) {
      this.param[key] = val
    },

    getInitialData() {
    },
    //
    cariRencanaBeli() {
      this.loading = true
      console.log('rencana beli ', this.param)
      const params = { params: this.param }
      return new Promise(resolve => {
        api.get('v1/simrs/farmasinew/listrencanabeli', params)
          .then(resp => {
            this.loading = false
            console.log('list rencana', resp)
            resolve(resp)
          })
          .catch(() => {
            this.loading = false
          })
      })
    },
    enterCariRencanaBeli(evt) {
      const val = evt.target.value
      this.setParam('no_rencbeliobat', val)
      this.cariRencanaBeli()
    }
  }
})
